name: yacht
services:
    yacht:
        cpu_shares: 90
        command: []
        container_name: yacht
        deploy:
            resources:
                limits:
                    memory: "16198402048"
        hostname: yacht
        image: selfhostedpro/yacht:latest
        labels:
            icon: http://172.16.254.130:8000/img/icons/apple-touch-icon-152x152.png
        networks:
            default: null
        ports:
            - mode: ingress
              target: 8000
              published: "8000"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: volume
              source: yacht
              target: /config
              volume: {}
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
              bind:
                create_host_path: true
networks:
    default:
        name: yacht_default
volumes:
    yacht:
        name: yacht_yacht
x-casaos:
    author: self
    category: self
    hostname: ""
    icon: http://172.16.254.130:8000/img/icons/apple-touch-icon-152x152.png
    index: /
    is_uncontrolled: false
    port_map: "8000"
    scheme: http
    title:
        custom: Yacht
